### ISSUE TITLE
KeyError: tensor(17)

### ISSUE THREAD

**Issue by JJJackssson** [CaptainEven/VideoCaption#1]
when i ran the code,an error occurred like following,any help will be appreciated greatly
Traceback (most recent call last):
  File "D:\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "D:\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2017.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pyWorkspace/VideoCaption/videoCaption.py", line 123, in <module>
    video2txt(in_file)
  File "D:/pyWorkspace/VideoCaption/videoCaption.py", line 73, in video2txt
    txts += generate_txt(img, tr4s, resnet50, cap_model, opt.use_gpu)
  File "D:/pyWorkspace/VideoCaption\img2txt.py", line 105, in generate_txt
    results = model.generate(img_feats.data[0])
  File "D:/pyWorkspace/VideoCaption\model.py", line 65, in generate
    sentence =  self.ix2word[idx]
KeyError: tensor(17)

**Comment by JJJackssson** [comment]
i have solved the question.

**Comment by JJJackssson** [comment]
sorry to bother you,i have solved the error

**Comment by autogyro** [comment]
JJJacksssson
how to resolve it? I also meet that problems, many thanks.

**Comment by JJJackssson** [comment]
@autogyro for me,just modify the code like this:
D:/pyWorkspace/VideoCaption\model.py, line 63, in generate
sentences = [' '.join([self.ix2word[int(idx)] for idx in sent]) for sent in sentences]
